version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=foyerdb
    volumes:
      - db:/var/lib/mysql

  tp-foyer:
    depends_on:
      - mysqldb
    image: ziedfadhlaoui/tp-foyer:1.0.0
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysqldb:3306/foyerdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC'
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: 'root'
    stdin_open: true
    tty: true

volumes:
  db:
